### PR TITLE
Stop propagation of cmd+a when column header or tab editor is open

### LINKED ISSUE #1095: CMD+A keyboard doesn't work in column header cell editor
**Works in formulas**
1. Open a cell editor that has a formula in it
2. Press CMD + A to select the entire formula to edit. 
3. It works. Nice

**Does not work in column headers**
1. Open a column header 
2. Press CMD + A to select the entire column header to change
3. It closes the cell editor and selects the entire sheet.

https://github.com/mito-ds/mito/assets/18709905/6b76915a-e00b-4a3a-8adb-8b237954907e

### PR DESCRIPTION
**Pull request by marthacryan**
Fixes #1095. Adds a helper util to call in the `onKeyDown` event for the column header and tab name input divs to use.

### CODE REVIEW

File: mitosheet/src/mito/types.tsx [hunk 1]
```diff
@@ -828,6 +828,12 @@ export interface KeyboardShorcut {
     // the command registered to that ID in plugin.tsx.
     jupyterLabCommand?: string
 
+    /**
+     * Some keyboard shortcuts should only be triggered if the user is not in a text input. 
+     * For example. cmd+a
```
Comment (naterush) [inline mitosheet/src/mito/types.tsx:833]: a little more here -- cmd + a should select the entire text input, not data in the sheet.

File: mitosheet/src/mito/types.tsx [hunk 2]
```diff
@@ -818,7 +818,7 @@ export interface KeyBinding {
     metaKey?: boolean;
 }
 
-export interface KeyboardShorcut {
+export interface KeyboardShortcut {
```
Comment (naterush) [inline mitosheet/src/mito/types.tsx:821]: Nice catch :)

**Review by naterush — COMMENTED** [review]
We need to add to:
1. Cmd + C
2. Cmd + Z?
3. Cmd + Y?

Infrastructure looks good -- this is def the right approach here :)

**Comment by naterush** [comment]
Oh, do you wanna add a little test for this one? You can just do Command + A for column headers, just so we have at least one sanity check on this.
