### PR TITLE
Do not display 'Fix Error in AI Chat' button for warnings

### LINKED ISSUE #1339: Mito AI debug error in chat button doesn't work for warnings
The `Resolve error in chat` button is displayed whenever the `application/vnd.jupyter.stderr` mime type is used. However, Jupyter uses this same mime type for errors and warning. 

When this is just a warning however, the error debugger does not work because the warning message doesn't have the `error.ename` or `error.evalue` fields that the button relies on. 

Screenshot 2024-10-14 at 8 37 17 AM

### PR DESCRIPTION
**Pull request by ktaletsk**
Fixes #1339

This PR:
- only displays 'Fix Error in AI Chat' button for errors, not warnings
- colors warnings yellow
- replaces deprecated `ReactDOM.render` with `createRoot`

# Description

Handle errors and warnings differently 
- warnings use yellow background to visually distinguish from errors
- do not show chat button for warnings

image

### CODE REVIEW

File: mito-ai/src/Extensions/ErrorMimeRenderer/ErrorMimeRendererPlugin.tsx [hunk 1]
```diff
@@ -64,14 +64,34 @@ class AugmentedStderrRenderer extends Widget implements IRenderMime.IRenderer {
...
+        this.node.appendChild(resolveInChatDiv);
+        
+        // Render the original content
         await this.originalRenderer.renderModel(model);
-        this.node.appendChild(this.originalRenderer.node);
+        const originalNode = this.originalRenderer.node;
+
+        // Apply styling for warnings
+        if (!isErrorMessage) {
+            originalNode.style.background = 'var(--jp-warn-color3)';
```
Comment (aarondr77) [inline mito-ai/src/Extensions/ErrorMimeRenderer/ErrorMimeRendererPlugin.tsx:90]: This looks awesome on light mode, but the text becomes hard to read in dark mode. 

Is there an easy fix for this? Now that we're touching more of the Jupyter UI, I want to do a better job of supporting dark mode as well. 

Screenshot 2024-12-20 at 10 33 36 AM

File: mito-ai/src/Extensions/ErrorMimeRenderer/ErrorMimeRendererPlugin.tsx [hunk 2]
```diff
@@ -64,14 +64,34 @@ class AugmentedStderrRenderer extends Widget implements IRenderMime.IRenderer {
     /**
      * Render the original error message and append the custom prompt.
      */
-    async renderModel(model: IRenderMime.IMimeModel): Promise<void> {    
+    async renderModel(model: IRenderMime.IMimeModel): Promise<void> {
+        // Determine if it's an error or a warning
+        const isErrorMessage = 'application/vnd.jupyter.error' in model.data;
```
Comment (aarondr77) [inline mito-ai/src/Extensions/ErrorMimeRenderer/ErrorMimeRendererPlugin.tsx:69]: Would be great to write one small playwright test that just checks when it's a warning the button is not there. 

We write all of our frontend tests in the `mito/tests` folder. You can add a test to the [mitoai.spec.ts](https://github.com/mito-ds/mito/blob/dev/tests/mitoai_ui_tests/mitoai.spec.ts) file. [Here's a test](https://github.com/mito-ds/mito/blob/471766527d7aa64bc87d0b7518bc0072dac52a7f/tests/mitoai_ui_tests/mitoai.spec.ts#L222) that checks if the AI debug button exists that might be a good starting place! 

There's a readme at the top of the `mito/tests` folder with instructions on how to set up the testing locally. There's slightly different commands depending on what part of Mito you are testing, so you can follow the Mac setup commands followed by the Mito AI commands. 

The reason the CI is not passing on this PR is because it's opened as a fork instead of just cloning the repo. Forked PRs don't get access to our CI secrets, as far as I know. Feel free to merge this PR without the test and then open another cloned PR for the frontend test so you can see that it passes.

**Review by aarondr77 — COMMENTED** [review]
Nice work on your first Mito PR! This feature is working well + thanks for cleaning up the `ReactDom` as well. 

Since this is your first contribution to this codebase, can you check out our CLA here: https://github.com/mito-ds/monorepo/blob/dev/CLA.md. If you agree, just hit me back in a comment with "I have read the CLA Document and I hereby sign the CLA"

**Comment by ktaletsk** [comment]
I have read the CLA Document and I hereby sign the CLA

File: mito-ai/src/Extensions/ErrorMimeRenderer/ErrorMimeRendererPlugin.tsx (hunk 1 above)
Comment (ktaletsk) [reply mito-ai/src/Extensions/ErrorMimeRenderer/ErrorMimeRendererPlugin.tsx]: _JupyterLab Dark_
image
_JupyterLab Dark High Contrast_
image
_JupyterLab Light_
image

**Comment by aarondr77** [comment]
I didn't have write access to this forked PR, so I ended up pushing a commit to my remote origin, but I think this will fix it: https://github.com/mito-ds/mito/commit/f408384fd280dc09a680fbfc13f474051ffc5f1a

The warning tests that you just created were not passing locally for me, but they are with this change to the write cell utility.

File: mito-ai/src/Extensions/ErrorMimeRenderer/ErrorMimeRendererPlugin.tsx [hunk 3]
```diff
@@ -64,14 +64,41 @@ class AugmentedStderrRenderer extends Widget implements IRenderMime.IRenderer {
...
+        this.node.appendChild(resolveInChatDiv);
+        
+        // Render the original content
         await this.originalRenderer.renderModel(model);
-        this.node.appendChild(this.originalRenderer.node);
+        const originalNode = this.originalRenderer.node;
+
+        // Apply styling for warnings
+        if (!isErrorMessage) {
+            // Find the pre element inside originalNode and apply styles to it as well
```
Comment (aarondr77) [inline mito-ai/src/Extensions/ErrorMimeRenderer/ErrorMimeRendererPlugin.tsx:90]: Can we set the background color on the original node too? Looks like that still has the red background on it. 
Screenshot 2024-12-23 at 10 06 52 PM

**Review by aarondr77 — APPROVED** [review]
Okay sweet! This is looking good. I think I figured out what was wrong with the tests and shared some updated code with you. Sorry for the trouble. 

Besides that, can we just update the other background on the original Node so the color is uniform for the full message? Then LGTM without another review.

File: mito-ai/src/Extensions/ErrorMimeRenderer/ErrorMimeRendererPlugin.tsx (hunk 3 above)
Comment (ktaletsk) [reply mito-ai/src/Extensions/ErrorMimeRenderer/ErrorMimeRendererPlugin.tsx]: Ah, my bad. The background coloring can be applied just to the original node (without digging into child element), but the text color needs to be changed directly in the child element.

**Comment by aarondr77** [comment]
Looks like the tests are continuing to fail, but it doesn't look like it's related to changes we made here. I can spend some time improving our testing tomorrow to try to fix this up. I can take it from here. 

Congrats on your first contribution! Sorry for the testing infra overhead!
