### PR TITLE
Fix code params bug

### LINKED ISSUE #1155: Code configuration options generate invalid param names for file imports
**Describe the bug**

1. Import a CSV file
2. Go to code config, and generate a function
3. Add a parameter for the CSV file
4. See that it inputs the `r` string

Screen Shot 2024-01-19 at 10 11 47 AM

We absolutely should add tests for this -- it's been buggy before.

### PR DESCRIPTION
**Pull request by marthacryan**
Fixes #1155.

### CODE REVIEW

File: mitosheet/src/mito/components/taskpanes/CodeOptions/CodeOptionsParameters.tsx [hunk 1]
```diff
@@ -115,13 +113,15 @@ const CodeOptionsParameters = (props: CodeOptionsParametersProps): JSX.Element =
...
+                        {unparametizedParams.map((paramInfo, index) => {
+                            const paramValue = paramInfo[0];
+                            const paramSubtype = paramInfo[2];
                             const paramDescription = getParamDescriptionString(paramSubtype);
 
                             return (
                                 <DropdownItem
                                     key={index}
-                                    title={getParamDisplayString(paramValue, paramType)}
+                                    title={getParamDisplayString(paramValue, paramSubtype !== 'import_dataframe')}
```
Comment (naterush) [inline mitosheet/src/mito/components/taskpanes/CodeOptions/CodeOptionsParameters.tsx:124]: I might instead make this opt-in -- checking if it starts with `file_name` or `file_path` or whatever

Comment (naterush) [reply mitosheet/src/mito/components/taskpanes/CodeOptions/CodeOptionsParameters.tsx:124]: Instead of casing here, you could case inside of the function...

File: mitosheet/src/mito/components/taskpanes/CodeOptions/CodeOptionsParameters.tsx [hunk 2]
```diff
@@ -169,7 +169,7 @@ const CodeOptionsParameters = (props: CodeOptionsParametersProps): JSX.Element =
                     <Row key={index} justify='space-between' align='center'>
                         <Col span={8} offsetRight={2}>
                             <p title={paramValue}>
-                                {getParamDisplayString(paramValue, paramValue.startsWith('r"') || paramValue.startsWith("r'") || paramValue.startsWith("'") ? 'file_name' : 'df_name')}
+                                {getParamDisplayString(paramValue, paramValue.startsWith('r"') || paramValue.startsWith("r'") || paramValue.startsWith("'"))}
```
Comment (naterush) [inline mitosheet/src/mito/components/taskpanes/CodeOptions/CodeOptionsParameters.tsx:172]: Removing this param and casing inside of the function seems like a good call, I think -- if doable!

File: tests/streamlit_ui_tests/taskpanes/code_config.spec.ts [hunk 3]
```diff
@@ -18,6 +18,11 @@ test.describe('Code Config', () => {
 
   test('Configure Code to generate function with parameters', async ({ page }) => {
```
Comment (naterush) [inline tests/streamlit_ui_tests/taskpanes/code_config.spec.ts:19]: Can we add to this test that it adds a file path param and the default has _path in it and is a valid Python variable?

**Review by naterush — COMMENTED** [review]
Minor cleanup, then LGTM!
